### ISSUE TITLE
Result I got

### ISSUE THREAD

**Issue by unburn** [Vandermode/ERRNet#17]
input
![image](https://user-images.githubusercontent.com/38403003/67549806-a67d4400-f737-11e9-8fb0-47187472c43a.png)
output
![image](https://user-images.githubusercontent.com/38403003/67549826-b1d06f80-f737-11e9-94dd-75a076410d5a.png)
I tried to test one single image using the way the below question told.
The result tend not to be well as the result in the paper. So is there anything i've done wrong during testing.

**Comment by unburn** [comment]
Or could someone try to test the input I updated?

**Comment by Vandermode** [comment]
Hi, Thank you for your interest to our work. 
I think this is due to the domain gap between real images, which hampers the generalizability of our model. 

By the way, I think you can try [BDN](https://github.com/yangj1e/bdn-refremv), which might work better in your provided image.

Also, if applicable, you can also train our model based upon the dataset provided in BDN. I believe the resulting model would yield better visual result, though impairing its quantative performance.
