### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Carlyx** [Vandermode/ERRNet#19]
Hi, I used the pretrained model you provided to test your dataset. But it's not as good as your paper shows. Could you give me some advice on this problem? @Vandermode

**Comment by Vandermode** [comment]
hi，which dataset you tested?  The unaligned dataset?

**Comment by Carlyx** [comment]
Thanks for your reply. I tested both the real dataset of CEIL and the unaligned dataset, which are generally good, but some of them only weaken the reflection effect or remove part of the reflection.

**Comment by Carlyx** [comment]
Hi, I just tried it again. There is a good effect on eval(). I may not understand the difference between your eval() and test() functions in test_errnet.py.   Could you explain the function?

**Comment by Vandermode** [comment]
test() function is designed for testing images without ground truth, while eval() function is used for quantative evaluation. 

For real images from CEIL and unaligned dataset, since the pretrained model is only trained on aligned data, it might not work well on unaligned dataset.  I do not release the finetuned model for unaligned data.

**Comment by Vandermode** [comment]
In my opinion, the performance on real-world reflection data still largely depends on the quality of synthetic data, as there is a domain gap between different real datasets.

**Comment by Carlyx** [comment]
Oh, I got it. Thank you for the advice. Your work is awesome. I will train with unaligned data.
